### ISSUE TITLE
Imagerotator.js with strict MIME type checking

### ISSUE THREAD

**Issue by jbrada** [webrotate360/magento2-adhoc#2]
Hello,

We are facing the issue
`Refused to execute script from '(...)/WebRotate360_ProductViewerAdHoc/imagerotator/html/js/imagerotator.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`.

It seems like require JS can't load imagerotator.js because file is evaluated as application/octet-stream not javascript.

Solution which we found out was "unobscuring" original imagerotator.js eval code and everything is working right now.

Is there any reason for using eval at all? In my opinion its just security risk, which can opens up code for injection attacks.

Thank you.

**Comment by webrotate360** [comment]
Hi, hmm... eval is historically used by our builds to unpack the compressed script data and it hasn't been 
giving us or our clients any troubles so far. The script is used both online and offline (where gzip and such is not on or available). 

But I'm not sure how you managed to trigger the error assuming a correct MIME type was served by the web server for the script file. Do you mind sharing a link to your website so we can see the MIME types and/or content policy you server is passing to a browser or suggest what could be an issue?
